SuperAnimalConversionTables: null
Task: pigs-heart-rate-top
TrainingFraction:
- 0.95
alphavalue: 0.7
batch_size: 8
bodyparts:
- L ear base
- R ear base
- Mid snout
- Ext occipital protuberance
colormap: rainbow
corner2move2:
- 50
- 50
cropping: false
date: Jan20
default_augmenter: default
default_net_type: resnet_50
detector_batch_size: 1
detector_snapshotindex: -1
dotsize: 12
engine: pytorch
identity: null
iteration: 0
move2corner: true
multianimalproject: false
numframes2pick: 20
pcutoff: 0.6
project_path: /Users/wwirth/programming/roithepig/src/roithepig/workflow/models/top
scorer: Steven
skeleton:
- - L ear base
  - R ear base
- - L ear base
  - Mid snout
- - L ear base
  - Ext occipital protuberance
- - R ear base
  - Mid snout
- - R ear base
  - Ext occipital protuberance
- - Mid snout
  - Ext occipital protuberance
skeleton_color: black
snapshotindex: -1
start: 0
stop: 1
video_sets:
  ? /content/drive/MyDrive/pigs-heart-rate-top-dlc-2026-01-20/videos/Excellent-vlc-record-2025-12-02-23h56m49s-D10_S20250917132808_E20250917133629.mp4-.mp4
  : crop: 0, 2592, 0, 1944
  ? /content/drive/MyDrive/pigs-heart-rate-top-dlc-2026-01-20/videos/Excellent-vlc-record-2025-12-02-23h58m41s-D10_S20250917133629_E20250917134451.mp4-.mp4
  : crop: 0, 2592, 0, 1944
  ? /content/drive/MyDrive/pigs-heart-rate-top-dlc-2026-01-20/videos/Excellent.Long-vlc-record-2025-12-02-23h48m30s-D9_S20250917111932_E20250917112754.mp4-.mp4
  : crop: 0, 2592, 0, 1944
  ? /content/drive/MyDrive/pigs-heart-rate-top-dlc-2026-01-20/videos/Excellent.Long-vlc-record-2025-12-02-23h52m13s-D9_S20250917133500_E20250917134325.mp4-.mp4
  : crop: 0, 2592, 0, 1944
  ? /content/drive/MyDrive/pigs-heart-rate-top-dlc-2026-01-20/videos/Good-vlc-record-2025-12-02-23h33m18s-D2_S20250917115004_E20250917115825.mp4-.mp4
  : crop: 0, 2592, 0, 1944
  ? /content/drive/MyDrive/pigs-heart-rate-top-dlc-2026-01-20/videos/Good-vlc-record-2025-12-02-23h35m29s-D2_S20250917115004_E20250917115825.mp4-.mp4
  : crop: 0, 2592, 0, 1944
  ? /content/drive/MyDrive/pigs-heart-rate-top-dlc-2026-01-20/videos/Good-vlc-record-2025-12-02-23h41m34s-D5_S20250917111633_E20250917112452.mp4-.mp4
  : crop: 0, 2592, 0, 1944
x1: 0
x2: 640
y1: 277
y2: 624
